### ISSUE TITLE
jest exists before report is generated

### ISSUE THREAD

**Issue by RobertGary1** [Hargne/jest-html-reporter#19] opened 2017-12-05 20:17 UTC
The createReport method returns a promise structure. However, when index.js calls the createReport its not expecting a promise so the execution resumes. The report is never generated because jest exists before the writeFile method is ever called.

**Comment by Hargne** [comment] 2017-12-05 20:53
I will have a look at it ASAP!

**Comment by RobertGary1** [comment] 2017-12-05 22:08
Is it an option to use the synchronous I/O calls in nodeJs? Not sure what version of NodeJs introduced them.

**Comment by Hargne** [comment] 2017-12-05 22:18
I'm pretty sure it's been possible for a long time to do synchronous calls with fs (correct me if I'm wrong). I'm unsure if that's the solution in this case though. It is a little weird as I haven't heard this from anyone else using the plugin.
What version of Node are you using, by the way?

**Comment by RobertGary1** [comment] 2017-12-06 00:14
I'm using node.js v8.9.1

**Comment by Hargne** [comment] 2017-12-06 10:19
I have been trying to reproduce this issue, but without any luck. I'm wondering if there might be something related to the structure of the project that you are working on that causes this issue, since there haven't been any reported issues where the reports haven't been generated up until now.

Theoretically, the asynchronous method `createReport` should not be aborted just because Jest has initialized prior to it finishing. This is due to the fact that Jest expects the testResultsProcessor (this module) to instantaneously return back the test result (which is done at the end of _index.js_).

Would you mind attempting to debug what may cause this issue to occur and post any findings here?

Thanks!

**Comment by zeevrosental** [comment] 2017-12-26 08:09
if it helps, i noticed that no report is generated if jest is running with --forceExit.

it seems that it closes before the report is created.

**Comment by Hargne** [comment] 2017-12-26 12:10
Closing this for now. Re-open if you still think it is a relevant issue.

**Comment by zeevrosental** [comment] 2017-12-26 15:19
i think this is still a problem. other reporters are not creating this problem(junit reporter).

**Comment by Hargne** [comment] 2017-12-27 16:04
Is is possible to provide more details of the environment you ran the test on (together with `--forceExit`)?

I did a test in this project with `--forceExit` enabled and the test report was successfully generated.

**Comment by Hargne** [comment] 2018-02-19 11:30
There is a potential fix for this issue in v2.0.0 - see #33

**Comment by zeevrosental** [comment] 2018-02-20 06:26
Thank you very much!!

I will see if it works for me :-)

On Feb 19, 2018 13:30, "Johan Hargne" <notifications@github.com> wrote:

There is a potential fix for this issue in v2.0.0 - see #33
<https://github.com/Hargne/jest-html-reporter/pull/33>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Hargne/jest-html-reporter/issues/19#issuecomment-366662693>,
or mute the thread

**Comment by Hargne** [comment] 2018-02-20 18:33
@zeevrosental [v2.0.0](https://github.com/Hargne/jest-html-reporter/releases/tag/2.0.0) has now been released. I will mark this issue as resolved for now.

**Closed by Hargne** 2018-02-20 18:33 UTC
Labels: bug, help wanted
