### ISSUE TITLE
`includeConsoleLog: true` doesn't report console output for tests

### ISSUE THREAD

**Issue by ffos** [Hargne/jest-html-reporter#48] opened 2018-07-30 01:24 UTC
Setup:
Package.json
```json
  "devDependencies": {
    "stuff": "stuff",
    "jest": "23.3.0",
    "jest-html-reporter": "^2.4.2"
  },
"jest": {
    "reporters": [
      "default",
      [
        "./node_modules/jest-html-reporter",
        {
          "pageTitle": "Test Report",
          "includeFailureMsg": true,
          "includeConsoleLog": true,
          "outputPath": "report/index.html"
        }
      ]
    ]
  }
```

Console output:
```bash
  console.log apiAgent.js:17
    Requesting: GET to: /api/cs/v2/resolver?text=Butt%20pain;%20can%E2%80%9A%C3%84%C3%B4t%20lie%20down
(this is a passing test)

  console.log apiAgent.js:17
    Requesting: GET to: /api/cs/v2/resolver?text=neck
(this is a failing test)

  console.log apiAgent.js:27
    Receive body: <html><head><title>Apache Tomcat/7.0.84 - Error report</title><style><!-

```

The html output only shows:
```

Test GET endpoint | Test passing one:  | passed in 0.115s
-- | -- | --
Test GET endpoint | Test failing one: neckError: expect(received).toBe(expected) // Object.is equality

```

No mention of logs on the output

**Comment by Hargne** [comment] 2018-07-30 12:46
Hi,

Interesting! It's difficult to see straight away what might have gone wrong. 
Here's a few things to try to pin-point the issue:

Firstly I see that you are configuring Jest via package.json - make sure that you are putting the configurations at the very top as mentioned in the Jest manual:

> If you'd like to use your package.json to store Jest's config, the "jest" key should be used on the top level so Jest will know how to find your settings.
**source:** [https://jestjs.io/docs/en/configuration.html](https://jestjs.io/docs/en/configuration.html)

Please also give it a try by configuring Jest within a `jest.config.js` file

Secondly, I ran a test to see if there was any issues - it did work as intended, _please note that the console.log output is rendered below the test suite_.

Finally, it would be awesome if you could send over the tests from the test spec where the console.logs are defined!

Thanks!

**Comment by Benoit-Vasseur** [comment] 2019-01-31 14:36
Hello,

The console property is null in the data object :/.
I am using Jest 24. Do you have any idea why ?

![deepinscreenshot_select-area_20190131093629](https://user-images.githubusercontent.com/1382663/52061159-b4e95700-253b-11e9-8bc5-c54e8f3d65cb.png)

![deepinscreenshot_select-area_20190131093444](https://user-images.githubusercontent.com/1382663/52061061-88cdd600-253b-11e9-934c-79cc35ec940f.png)

**Comment by Hargne** [comment] 2019-02-01 04:14
Hi,

Is the console log situated within the code being tested or the actual test itself?
Jest will not pass on logs made in the test specs to the reporter.

**Comment by Benoit-Vasseur** [comment] 2019-02-01 21:04
Ooh. Well yes the console.log is in the test file :/.

Do you know a way to be able to have those console.log pass to the reporter (those made in spec files) ?

**Comment by Domiii** [comment] 2019-02-17 13:18
Same issue here.

> Jest will not pass on logs made in the test specs to the reporter.

Uhm... I just want to see all console output related to a test suit. So I guess getting basic `console.log` output is not possible?

Debugging `jest` tests has been a mess from the start. Because of it's "(pseudo-)multi-threaded nature", `console.log` calls appear in confusing order and sometimes get swallowed whole. I was hoping that this plugin would sort the corresponding `log` calls to the corresponding tests, but I guess that would not be easily achievable. I guess it is time for a proper `jest` logging tool... :/

**Comment by Hargne** [comment] 2019-03-07 10:51
Exactly: as of now, Jest does not forward any console.logs made within the test suites to the reporter - only those made within the actual code.

I will close this issue for now, but feel free to open it if you feel that it is still relevant.

**Closed by Hargne** 2019-03-07 10:51 UTC
